### Section A: Data Structures and Control Strutures

### 1.

In [ ]:
# creating a list
ls = [7, 2, 5, 9, 4]

In [ ]:
# Append to list
ls.append(4)
ls

In [ ]:
# extend the list, append multiple element.
ls.extend([7, 3, 5])
ls

In [ ]:
# insert: add the element at given position
ls.insert(2, 6)
ls

In [ ]:
# remove: removes the particular element.
ls.remove(4)
ls
# first element will be removed

In [ ]:
# pop: removes the last element of the list
ls.pop()
ls

In [ ]:
# index: give the element index
indx = ls.index(5)
indx

In [ ]:
# count: number of duplicate elements in the list
ct = ls.count(7)
ct

In [ ]:
# sort: sort the list 
ls.sort()
ls

In [ ]:
# reverse : reverse the list
ls.reverse()
ls

In [ ]:
# sort and reverse the lsit
ls.sort(reverse= True)
ls

In [ ]:
# clear: delete all the elemnts from the list
# ls.clear()
# ls

### 2.

In [ ]:
# creating tuple
tu = ('veer', 'viks', 'sham')
# trying to update the second element inside the tuple
tu[2] = 'sid'
tu
# tuple is immutable sequence here we can't change the elements by assigning values to them, and also can't add the elements for it.

### 3.

In [ ]:
# crating set
s1 = {2, 4, 5, 6, 2, 5, 4, 1}
s1
# a set will remove the duplicates and stores the values in unordered way.

### 4.

In [ ]:
# create dictionary
student = {
    'name': 'jon',
    'age': 28,
    'city': 'bang'
}
# updated age 
student['age'] = 30
# added new key value pair
student['email'] = 'jon@gmail.com'
student

### 5

In [ ]:
# script to check the voting elgibility
# user input 
age = int(input("Enter your age to check elgibilty for voting:"))
if age>=18:
    print("congratulations you are eligible to vote")
else:
    print("You can vote after turning 18 years old")

### 6.

In [ ]:
# finding grades for the marks
marks = int(input("Enter Marks"))
if marks >=90:
    print(f"{marks} : Grade: A")
elif marks >= 75:
    print(f"{marks} : Grade: B")
elif marks >= 50:
    print(f"{marks} : Grade: c")
else:
    print(f"{marks}: Fail")

### 7.

In [ ]:
# checking number is positive, nagative, even or zero
num = int(input("Enter a number"))
if num>0:
    if num % 2 == 0:
        print(f"{num} is positive and even")
    else:
        print(f"{num} is positive")
elif num == 0:
    print("it's Zero")
else:
    print(f"{num} is negative")    

In [ ]:
# tried other way also
if num<0:
    print("negative number")
elif num == 0:
    print("its zero")
elif num %2 == 0:
    print("pstv and even")
else:
    print("pstv")

### Section B: Numpy

### 8.

In [2]:
import numpy as np

In [ ]:
# A scalar using np.array
scalar = np.array(5)
print("Scalar:", scalar)

In [ ]:
# A 1D array with values 1 to 5
one_d = np.array([1, 2, 3, 4, 5])
print("1D Array:", one_d)

In [ ]:
# A 2D array (2x3) with values from 10 to 60 in steps of 10
two_d = np.array([[10, 20, 30],
                  [40, 50, 60]])
print("2D Array:\n", two_d)

### 9.

In [3]:
# 4*4 array of random integers between 0 to 100
arr = np.random.randint(0, 101, size=(4, 4))
print("4*4 random arry:\n", arr)

4*4 random arry:
 [[96 49 46 98]
 [ 0 37 45 63]
 [88 52 70 81]
 [58 86 67 57]]


### 10.

In [ ]:
#  crate 2D array of 3*3
two_d = np.array([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])
# convert 2D arry to pandas data frame with column name A, B & c
df = pd.DataFrame(two_d, columns= ['A', 'B', 'C'])
df

### Section C: Exploring Pandas

### 11.

In [ ]:
import pandas as pd

In [ ]:
# crating a data frame using list
lst_df = [
    ['jon', 22, 'bang', 10000],
    ['jim', 23, 'hyd', 50000],
    ['tom', 25, 'bag', 70000],
    ['tim', 22, 'bng', 40000],
    ['jan', 27, 'chn', 60000],
    ['feb', 30, 'maxi', 100000],
    ['sid', 35, 'vivtn', 90000],
    ['jim', 23, 'hyd', 50000],
    ['san', 33, 'chic', 100000],
    ['sam', 25, 'mumb', ],   
    
]

In [ ]:
# creating data frame and giving appropriate column names
df = pd.DataFrame(lst_df, columns=['name', 'age', 'city', 'salary'],)
df

In [ ]:
# using info function getting is there any missing valuses are there and how much entries there in file
df.info()

In [ ]:
# to get the standard devation, mean, quaterly value and min max values  from the data set
df.describe()

In [ ]:
#  filling missing value in salary using it's mean
df['salary'] = df['salary'].fillna(df['salary'].mean())
df

In [ ]:
# removing duplicate rows
new_df = df.drop_duplicates()
new_df

In [ ]:
# Droping city clolumn 
new_df1 = new_df.drop('city', axis=1)
new_df1